### ISSUE TITLE
ConnectionError: ('Connection aborted.', error(111, 'Connect ion refused'))

### ISSUE THREAD

**Issue by flik** [OpenBankProject/Hello-OBP-DirectLogin-Python#1]
python2 hello_obp.py
Login as {'dl_username': 'robert.x.0.gh@example.com', 'dl_password': '3e3a3102'} to http://127.0.0.1:8080/my/logins/direct
Traceback (most recent call last):
  File "hello_obp.py", line 31, in <module>
    response = requests.post(URL_LOGIN, json=loginData)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connect ion refused'))

**Comment by pbozin** [comment]
ABP-API needs to be running (in this case on http://127.0.0.1:8080)

dl_username and dl_password were replaced with username and password in recent versions
